spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        show_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${RDS_URL}
    username: ${RDS_ID}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 환경변수 처리로 해주세요.
#config:
#  domain: http//modudogcat-front.s3-website.ap-northeast-2.amazonaws.com
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420
config:
  domain: http://ec2-43-200-2-180.ap-northeast-2.compute.amazonaws.com:8080
  adminId: ${ADMIN_ID}