spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://database-1.ckzdqlg4gwg9.ap-northeast-2.rds.amazonaws.com:3306/database-1
    username: admin
    password: qwer1234
config:
  domain: http://http://modudogcat-front.s3-website.ap-northeast-2.amazonaws.com