# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "dev/be" ]

permissions:
  contents: read
  
env:
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Clean with Gradle
      run: ./gradlew clean
    - name: Build with Gradle
      run: ./gradlew build

    - name: Make zip file
      run: zip -r ./modudogcat.zip .
      shell: bash
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./${{ secrets.S3_BUCKET_NAME }}.zip s3://$S3_BUCKET_NAME/${{ secrets.S3_BUCKET_NAME }}.zip

    - name: Code Deploy
      env:
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      run: >
          aws deploy create-deployment --application-name ${{ secrets.S3_BUCKET_NAME }}
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name ${{ secrets.S3_BUCKET_NAME }}-group
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=${{ secrets.S3_BUCKET_NAME }}.zip
